### ISSUE TITLE
Série de sugestões

### ISSUE THREAD

**Issue by brcontainer** [stackuserflow/sopt-chrome-app#1]
- ▢ Adicionar fonte Roboto (CSS requisita, mas ela não esta no App)
- ▢ Imagens do `*.stack.imgur.com` estão bloqueadas.
- ▢ Alguns caracteres aparecem como "entidades"
- ▢ Adicionar um cache com o dados em formato JSON pra evitar múltiplas requisições e ainda poder detectar o que já foi baixado, com isto será possivel adicionar pushs/notificações no `browserAction`
- ✓ (visual) Fixar navbar e sidebar, no sidebar colocar um scrollbar próprio.
- ▢ Recomendo fixar uma largura limite no sidebar também (`min-width: ...;`)
- ▢ As fontes parecem estar com BLUR, isso incomoda a leitura, recomendo remover (Windows)
- ✓ Seria legal customizar os scrollbars pra algo como:
  
  ``` css
  ::-webkit-scrollbar {
      background: #dfdfdf;
      border-radius: 4px;
      width: 8px;
  }
  
  ::-webkit-scrollbar-thumb {
      background-color: rgba(0, 0, 0, 0.2);
      border-radius: 4px;
  }
  
  ::-webkit-scrollbar-thumb:hover {
      background-color: rgba(0, 0, 0, 0.5);
  }
  ```
